#!/usr/bin/env npx tsx
// scripts/generate-columns.ts
// Parses src/types/database.ts and generates src/schema/columns.ts
// with per-table column name constants + a lookup map for validation.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
const DB_TYPES_PATH = resolve(ROOT, 'src/types/database.ts');
const OUT_DIR = resolve(ROOT, 'src/schema');
const OUT_PATH = resolve(OUT_DIR, 'columns.ts');

const src = readFileSync(DB_TYPES_PATH, 'utf-8');

// Extract table names and their Row columns from the generated types.
// Pattern: <tableName>: { Row: { <col>: <type> \n ... } }
const tableRegex = /^\s{6}(\w+):\s*\{\s*\n\s*Row:\s*\{([^}]+)\}/gm;
const colRegex = /^\s+(\w+):/gm;

const tables = new Map<string, string[]>();
let match: RegExpExecArray | null;

while ((match = tableRegex.exec(src)) !== null) {
  const tableName = match[1]!;
  const rowBlock = match[2]!;
  const cols: string[] = [];
  let cm: RegExpExecArray | null;
  colRegex.lastIndex = 0;
  while ((cm = colRegex.exec(rowBlock)) !== null) {
    cols.push(cm[1]!);
  }
  if (cols.length > 0) {
    tables.set(tableName, cols);
  }
}

// Generate output
const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-columns.ts — DO NOT EDIT',
  '// Regenerate with: npm run schema:sync',
  '',
  `export const SCHEMA_GENERATED_AT = '${new Date().toISOString()}';`,
  '',
];

const sortedTables = [...tables.entries()].sort((a, b) => a[0].localeCompare(b[0]));

for (const [table, cols] of sortedTables) {
  lines.push(`export const ${table} = [${cols.map(c => `'${c}'`).join(', ')}] as const;`);
}

lines.push('');
lines.push('export const TABLE_COLUMNS: Record<string, readonly string[]> = {');
for (const [table] of sortedTables) {
  lines.push(`  ${table},`);
}
lines.push('};');
lines.push('');

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_PATH, lines.join('\n'));
console.log(`Generated ${OUT_PATH} — ${sortedTables.length} tables`);
