-- 065_ai_drafts.sql
-- AI Draft storage for Draft-Preview-Commit pattern
-- Stores temporary draft documents generated by AI tools for user review before commit

CREATE TABLE public.ai_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id),
  created_by UUID NOT NULL,
  session_id TEXT NOT NULL,

  action_type TEXT NOT NULL CHECK (action_type IN ('create', 'update', 'status_change')),
  resource_type TEXT NOT NULL,
  target_id UUID,
  content JSONB NOT NULL,
  original_content JSONB,

  tool_name TEXT NOT NULL,
  tool_args JSONB NOT NULL DEFAULT '{}',

  summary JSONB NOT NULL DEFAULT '{}',

  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'committed', 'discarded', 'expired')),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  renewed_count INTEGER NOT NULL DEFAULT 0,
  committed_at TIMESTAMPTZ,
  committed_record_id UUID,
  discarded_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_ai_drafts_org_user ON ai_drafts(organization_id, created_by);
CREATE INDEX idx_ai_drafts_session ON ai_drafts(session_id);
CREATE INDEX idx_ai_drafts_pending ON ai_drafts(status) WHERE status = 'pending';
CREATE INDEX idx_ai_drafts_expires ON ai_drafts(expires_at) WHERE status = 'pending';
CREATE INDEX idx_ai_drafts_resource ON ai_drafts(resource_type, target_id) WHERE status = 'pending';

CREATE TRIGGER trg_ai_drafts_updated
  BEFORE UPDATE ON ai_drafts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE ai_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ai_drafts_select" ON ai_drafts FOR SELECT TO authenticated
  USING (organization_id = get_user_org_id());

CREATE POLICY "ai_drafts_insert" ON ai_drafts FOR INSERT TO authenticated
  WITH CHECK (organization_id = get_user_org_id());

CREATE POLICY "ai_drafts_update" ON ai_drafts FOR UPDATE TO authenticated
  USING (organization_id = get_user_org_id() AND created_by = (auth.uid())::UUID);

CREATE POLICY "ai_drafts_delete" ON ai_drafts FOR DELETE TO authenticated
  USING (organization_id = get_user_org_id() AND created_by = (auth.uid())::UUID);

CREATE OR REPLACE FUNCTION public.cleanup_expired_drafts()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  expired_count INTEGER;
BEGIN
  UPDATE ai_drafts
  SET status = 'expired', updated_at = NOW()
  WHERE status = 'pending'
    AND expires_at < NOW()
    AND deleted_at IS NULL;
  GET DIAGNOSTICS expired_count = ROW_COUNT;
  RETURN expired_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.purge_old_drafts()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  purged_count INTEGER;
BEGIN
  UPDATE ai_drafts
  SET deleted_at = NOW()
  WHERE status IN ('expired', 'discarded', 'committed')
    AND updated_at < NOW() - INTERVAL '7 days'
    AND deleted_at IS NULL;
  GET DIAGNOSTICS purged_count = ROW_COUNT;
  RETURN purged_count;
END;
$$;
