// AUTO-GENERATED — DO NOT EDIT
// Regenerate with: npm run schema:sync (runs generate-check-constraints.ts)
// Source: live DB pg_constraint (public schema, CHECK type with ANY/ARRAY pattern)

export const CONSTRAINTS_GENERATED_AT = '2026-04-21T21:55:00.000Z';

export interface CheckConstraint {
  table: string;
  column: string;
  values: string[];
}

export const CHECK_CONSTRAINTS: CheckConstraint[] = [
  { table: 'account_subjects', column: 'balance_direction', values: ['debit', 'credit'] },
  { table: 'account_subjects', column: 'category', values: ['asset', 'liability', 'equity', 'revenue', 'expense'] },
  { table: 'account_subjects', column: 'status', values: ['active', 'inactive'] },
  { table: 'advance_shipment_notices', column: 'status', values: ['open', 'received', 'cancelled'] },
  { table: 'agent_decisions', column: 'approval_status', values: ['na', 'pending', 'approved', 'rejected', 'expired'] },
  { table: 'agent_decisions', column: 'execution_status', values: ['pending', 'executing', 'success', 'failed', 'cancelled', 'blocked'] },
  { table: 'agent_decisions', column: 'risk_level', values: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5'] },
  { table: 'agent_sessions', column: 'session_type', values: ['chat', 'task', 'workflow', 'scheduled'] },
  { table: 'agent_sessions', column: 'status', values: ['active', 'completed', 'aborted', 'expired'] },
  { table: 'approval_records', column: 'document_type', values: ['purchase_order', 'sales_order', 'payment_request', 'supplier_invoice', 'sales_invoice', 'budget', 'work_order'] },
  { table: 'approval_records', column: 'status', values: ['pending', 'approved', 'rejected', 'recalled'] },
  { table: 'approval_rule_steps', column: 'approval_type', values: ['sequential', 'parallel', 'any_one'] },
  { table: 'asset_maintenance_records', column: 'maintenance_type', values: ['routine', 'repair', 'overhaul'] },
  { table: 'budgets', column: 'budget_type', values: ['annual', 'quarterly', 'monthly', 'project'] },
  { table: 'budgets', column: 'status', values: ['draft', 'approved', 'active', 'closed'] },
  { table: 'business_events', column: 'entity_type', values: ['purchase_order', 'sales_order', 'supplier_invoice', 'sales_invoice', 'work_order', 'inventory', 'payment_request', 'system', 'product', 'customer', 'supplier', 'warehouse', 'employee', 'contract', 'fixed_asset', 'quality_inspection', 'budget', 'purchase_receipt', 'sales_shipment', 'sales_return', 'purchase_requisition', 'rfq', 'voucher', 'payment_record', 'customer_receipt', 'bom', 'approval'] },
  { table: 'business_events', column: 'severity', values: ['info', 'warning', 'critical'] },
  { table: 'carriers', column: 'carrier_type', values: ['express', 'freight', 'ltl', 'ftl', 'ocean', 'air'] },
  { table: 'contract_items', column: 'status', values: ['open', 'fulfilled', 'cancelled'] },
  { table: 'contracts', column: 'contract_type', values: ['sales', 'procurement', 'service', 'framework'] },
  { table: 'contracts', column: 'party_type', values: ['customer', 'supplier'] },
  { table: 'contracts', column: 'status', values: ['draft', 'active', 'expired', 'terminated', 'cancelled', 'completed'] },
  { table: 'customer_addresses', column: 'address_type', values: ['billing', 'shipping', 'both'] },
  { table: 'customer_receipts', column: 'payment_method', values: ['cash', 'bank_transfer', 'alipay', 'wechat', 'check', 'other'] },
  { table: 'customer_receipts', column: 'reference_type', values: ['sales_invoice', 'sales_order'] },
  { table: 'customer_receipts', column: 'status', values: ['draft', 'confirmed', 'reconciled', 'cancelled'] },
  { table: 'customers', column: 'status', values: ['active', 'inactive', 'suspended'] },
  { table: 'customers', column: 'type', values: ['individual', 'company', 'corporate', 'enterprise', 'government', 'other'] },
  { table: 'defect_codes', column: 'severity', values: ['minor', 'major', 'critical'] },
  { table: 'departments', column: 'status', values: ['active', 'inactive'] },
  { table: 'document_attachments', column: 'entity_type', values: ['purchase_order', 'sales_order', 'supplier_invoice', 'sales_invoice', 'work_order', 'inventory', 'payment_request', 'system', 'product', 'customer', 'supplier', 'contract', 'fixed_asset', 'quality_inspection', 'purchase_receipt', 'sales_shipment'] },
  { table: 'document_relations', column: 'from_object_type', values: ['purchase_requisition', 'purchase_order', 'purchase_receipt', 'sales_order', 'sales_shipment', 'sales_return', 'supplier_invoice', 'sales_invoice', 'payment_request', 'payment_record', 'customer_receipt', 'contract', 'work_order', 'quality_inspection', 'voucher', 'budget', 'fixed_asset'] },
  { table: 'document_relations', column: 'to_object_type', values: ['purchase_requisition', 'purchase_order', 'purchase_receipt', 'sales_order', 'sales_shipment', 'sales_return', 'supplier_invoice', 'sales_invoice', 'payment_request', 'payment_record', 'customer_receipt', 'contract', 'work_order', 'quality_inspection', 'voucher', 'budget', 'fixed_asset'] },
  { table: 'employees', column: 'position', values: ['admin', 'manager', 'sales', 'purchasing', 'inventory', 'finance', 'production', 'user'] },
  { table: 'employees', column: 'status', values: ['active', 'inactive', 'terminated'] },
  { table: 'exchange_rates', column: 'rate_type', values: ['spot', 'average', 'budget', 'closing'] },
  { table: 'fixed_assets', column: 'depreciation_method', values: ['straight_line', 'declining_balance'] },
  { table: 'fixed_assets', column: 'status', values: ['active', 'disposed', 'under_maintenance'] },
  { table: 'import_logs', column: 'status', values: ['processing', 'completed', 'failed'] },
  { table: 'inventory_counts', column: 'status', values: ['draft', 'in_progress', 'completed', 'cancelled'] },
  { table: 'inventory_lots', column: 'status', values: ['available', 'quarantine', 'expired', 'consumed'] },
  { table: 'inventory_reservations', column: 'reference_type', values: ['sales_order', 'work_order', 'transfer_order', 'purchase_order'] },
  { table: 'inventory_reservations', column: 'status', values: ['active', 'released', 'cancelled', 'expired', 'consumed'] },
  { table: 'message_feedback', column: 'feedback', values: ['good', 'bad'] },
  { table: 'notifications', column: 'entity_type', values: ['purchase_order', 'sales_order', 'supplier_invoice', 'sales_invoice', 'payment_request', 'payment_record', 'customer_receipt', 'contract', 'work_order', 'purchase_receipt', 'sales_shipment', 'sales_return', 'quality_inspection', 'approval', 'budget', 'fixed_asset', 'system', 'product', 'customer', 'supplier', 'warehouse', 'employee'] },
  { table: 'notifications', column: 'notification_type', values: ['info', 'warning', 'action_required', 'approval', 'system'] },
  { table: 'organizations', column: 'plan', values: ['free', 'standard', 'enterprise'] },
  { table: 'organizations', column: 'status', values: ['active', 'inactive'] },
  { table: 'payment_records', column: 'partner_type', values: ['customer', 'supplier'] },
  { table: 'payment_records', column: 'payment_method', values: ['cash', 'bank_transfer', 'check', 'other'] },
  { table: 'payment_records', column: 'payment_type', values: ['receivable', 'payable'] },
  { table: 'payment_records', column: 'reference_type', values: ['supplier_invoice', 'sales_invoice', 'payment_request'] },
  { table: 'payment_records', column: 'status', values: ['draft', 'confirmed', 'cancelled'] },
  { table: 'payment_requests', column: 'payment_method', values: ['bank_transfer', 'check', 'cash', 'other'] },
  { table: 'payment_requests', column: 'status', values: ['draft', 'submitted', 'approved', 'paid', 'rejected', 'cancelled'] },
  { table: 'portal_users', column: 'role', values: ['supplier', 'supplier_admin'] },
  { table: 'portal_users', column: 'status', values: ['active', 'inactive', 'suspended'] },
  { table: 'price_lists', column: 'status', values: ['active', 'inactive', 'draft'] },
  { table: 'product_cost_history', column: 'cost_method', values: ['weighted_average', 'fifo', 'standard'] },
  { table: 'product_cost_history', column: 'reference_type', values: ['purchase_receipt', 'sales_shipment', 'work_order', 'adjustment', 'inventory_count', 'initial', 'return', 'sales_return', 'transfer'] },
  { table: 'products', column: 'status', values: ['active', 'inactive', 'discontinued', 'draft'] },
  { table: 'products', column: 'type', values: ['product', 'material', 'semi_finished', 'service', 'consumable', 'asset'] },
  { table: 'purchase_orders', column: 'status', values: ['draft', 'submitted', 'approved', 'rejected', 'in_transit', 'partially_received', 'received', 'closed', 'cancelled'] },
  { table: 'purchase_receipts', column: 'status', values: ['draft', 'confirmed', 'cancelled'] },
  { table: 'purchase_requisitions', column: 'status', values: ['draft', 'submitted', 'approved', 'rejected', 'cancelled', 'converted'] },
  { table: 'quality_inspection_items', column: 'check_result', values: ['pass', 'fail'] },
  { table: 'quality_inspections', column: 'reference_type', values: ['purchase_receipt', 'work_order', 'sales_return', 'in_process', 'final'] },
  { table: 'quality_inspections', column: 'result', values: ['pending', 'pass', 'fail', 'conditional'] },
  { table: 'quality_inspections', column: 'status', values: ['draft', 'in_progress', 'completed', 'cancelled'] },
  { table: 'reconciliation_statements', column: 'status', values: ['draft', 'confirmed', 'closed', 'cancelled'] },
  { table: 'rfq_headers', column: 'status', values: ['draft', 'issued', 'closed', 'cancelled'] },
  { table: 'sales_invoices', column: 'status', values: ['draft', 'issued', 'paid', 'overdue', 'voided', 'cancelled'] },
  { table: 'sales_orders', column: 'payment_status', values: ['unpaid', 'partial', 'paid'] },
  { table: 'sales_orders', column: 'status', values: ['draft', 'submitted', 'confirmed', 'approved', 'rejected', 'shipping', 'shipped', 'completed', 'cancelled'] },
  { table: 'sales_returns', column: 'status', values: ['draft', 'approved', 'received', 'rejected', 'cancelled'] },
  { table: 'sales_shipments', column: 'status', values: ['draft', 'confirmed', 'shipped', 'delivered', 'cancelled'] },
  { table: 'schema_registry', column: 'risk_level', values: ['low', 'medium', 'high'] },
  { table: 'schema_registry', column: 'status', values: ['draft', 'active', 'archived'] },
  { table: 'serial_numbers', column: 'status', values: ['in_stock', 'sold', 'scrapped', 'returned'] },
  { table: 'shipment_tracking_events', column: 'event_type', values: ['picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'returned'] },
  { table: 'stock_transactions', column: 'reference_type', values: ['purchase', 'sales', 'production', 'adjustment', 'transfer', 'return', 'purchase_receipt', 'sales_shipment', 'sales_return', 'work_order', 'inventory_count', 'initial'] },
  { table: 'stock_transactions', column: 'transaction_type', values: ['in', 'out', 'transfer', 'adjust'] },
  { table: 'supplier_certificates', column: 'status', values: ['valid', 'expiring', 'expired'] },
  { table: 'supplier_invoices', column: 'status', values: ['draft', 'received', 'verified', 'approved', 'paid', 'disputed', 'cancelled'] },
  { table: 'supplier_quotations', column: 'status', values: ['received', 'evaluated', 'selected', 'rejected'] },
  { table: 'suppliers', column: 'status', values: ['active', 'inactive', 'blocked', 'pending_approval'] },
  { table: 'suppliers', column: 'supplier_type', values: ['product', 'service', 'logistics', 'subcontract', 'other'] },
  { table: 'three_way_match_results', column: 'match_status', values: ['pending', 'matched', 'partial', 'mismatch', 'disputed'] },
  { table: 'tool_registry', column: 'risk_level', values: ['D0', 'D1', 'D2', 'D3', 'D4', 'D5'] },
  { table: 'uoms', column: 'uom_type', values: ['quantity', 'weight', 'volume', 'length', 'area', 'time', 'other'] },
  { table: 'voucher_entries', column: 'entry_type', values: ['debit', 'credit'] },
  { table: 'vouchers', column: 'status', values: ['draft', 'approved', 'posted', 'voided', 'cancelled'] },
  { table: 'vouchers', column: 'voucher_type', values: ['receipt', 'payment', 'transfer', 'general'] },
  { table: 'warehouses', column: 'status', values: ['active', 'inactive'] },
  { table: 'warehouses', column: 'type', values: ['finished_goods', 'raw_materials', 'semi_finished', 'transit', 'virtual'] },
  { table: 'work_order_materials', column: 'status', values: ['pending', 'partial', 'issued', 'cancelled'] },
  { table: 'work_orders', column: 'status', values: ['draft', 'released', 'in_progress', 'completed', 'cancelled'] },
  { table: 'workflow_steps', column: 'status', values: ['pending', 'in_progress', 'completed', 'skipped'] },
  { table: 'workflows', column: 'entity_type', values: ['purchase_order', 'sales_order', 'supplier_invoice', 'sales_invoice', 'work_order', 'inventory', 'payment_request', 'system', 'contract', 'fixed_asset', 'quality_inspection', 'budget', 'purchase_receipt'] },
  { table: 'workflows', column: 'status', values: ['pending', 'in_progress', 'completed', 'cancelled', 'failed'] },
];

// Lookup helpers
export const CONSTRAINT_LOOKUP = new Map<string, Map<string, Set<string>>>();
for (const c of CHECK_CONSTRAINTS) {
  if (!CONSTRAINT_LOOKUP.has(c.table)) CONSTRAINT_LOOKUP.set(c.table, new Map());
  CONSTRAINT_LOOKUP.get(c.table)!.set(c.column, new Set(c.values));
}
