// AUTO-GENERATED by scripts/generate-columns.ts — DO NOT EDIT
// Regenerate with: npm run schema:sync

export const SCHEMA_GENERATED_AT = '2026-04-28T10:45:42.335Z';

export const account_subjects = ['balance_direction', 'category', 'code', 'created_at', 'id', 'is_leaf', 'name', 'organization_id', 'parent_id', 'status', 'updated_at'] as const;
export const advance_shipment_notices = ['asn_no', 'created_at', 'created_by', 'deleted_at', 'expected_date', 'id', 'organization_id', 'po_id', 'remark', 'status', 'supplier_id', 'updated_at', 'warehouse_id'] as const;
export const agent_decisions = ['agent_id', 'agent_version', 'approval_status', 'approved_at', 'approver', 'confidence', 'context_refs', 'created_at', 'decision', 'delegated_by', 'error_message', 'execution_status', 'human_approval_req', 'human_modification', 'id', 'model_profile', 'organization_id', 'outcome', 'reasoning_summary', 'risk_level', 'session_id', 'tools_called', 'trigger_event_id', 'trigger_event_version'] as const;
export const agent_sessions = ['agent_id', 'context', 'created_at', 'ended_at', 'id', 'message_count', 'organization_id', 'session_type', 'started_at', 'status', 'user_id'] as const;
export const approval_records = ['comments', 'created_at', 'created_by', 'decision_at', 'decision_by', 'decision_level', 'deleted_at', 'document_id', 'document_type', 'id', 'organization_id', 'rule_id', 'status', 'updated_at'] as const;
export const approval_rule_steps = ['approval_type', 'approver_role', 'created_at', 'id', 'min_approvers', 'rule_id', 'step_order', 'timeout_hours'] as const;
export const approval_rules = ['created_at', 'deleted_at', 'document_type', 'id', 'is_active', 'max_amount', 'min_amount', 'organization_id', 'required_roles', 'rule_name', 'sequence_order', 'updated_at'] as const;
export const asn_lines = ['asn_id', 'created_at', 'deleted_at', 'id', 'item_id', 'line_number', 'lot_no', 'organization_id', 'po_line_id', 'quantity', 'unit_id'] as const;
export const asset_depreciations = ['accumulated_depreciation', 'asset_id', 'book_value_after', 'created_at', 'depreciation_amount', 'id', 'period_month', 'period_year', 'posted', 'posted_at'] as const;
export const asset_maintenance_records = ['asset_id', 'cost', 'created_at', 'deleted_at', 'description', 'id', 'maintenance_type', 'next_due_at', 'performed_at', 'performed_by'] as const;
export const auth_events = ['created_at', 'event_type', 'id', 'ip_address', 'metadata', 'organization_id', 'user_agent', 'user_id'] as const;
export const bom_headers = ['bom_number', 'created_at', 'created_by', 'effective_date', 'id', 'is_active', 'notes', 'organization_id', 'product_id', 'quantity', 'updated_at', 'version'] as const;
export const bom_items = ['bom_header_id', 'id', 'notes', 'product_id', 'quantity', 'scrap_rate', 'sequence', 'unit'] as const;
export const budget_lines = ['account_code', 'actual_amount', 'budget_id', 'cost_center_id', 'created_at', 'deleted_at', 'description', 'id', 'period_month', 'planned_amount', 'updated_at', 'variance_amount'] as const;
export const budgets = ['approved_at', 'approved_by', 'budget_name', 'budget_type', 'budget_year', 'created_at', 'currency', 'deleted_at', 'id', 'notes', 'organization_id', 'status', 'total_amount', 'updated_at'] as const;
export const business_events = ['causation_id', 'correlation_id', 'entity_id', 'entity_type', 'event_type', 'event_version', 'id', 'idempotency_key', 'occurred_at', 'organization_id', 'payload', 'processed', 'severity', 'source_system'] as const;
export const carriers = ['carrier_type', 'code', 'contact', 'created_at', 'deleted_at', 'id', 'is_active', 'name', 'organization_id', 'phone', 'tracking_url_template', 'updated_at'] as const;
export const component_whitelist = ['allowed_roles', 'component_name', 'component_type', 'created_at', 'description', 'id'] as const;
export const contract_items = ['amount', 'contract_id', 'created_at', 'deleted_at', 'id', 'notes', 'product_id', 'quantity', 'status', 'tax_rate', 'unit_price'] as const;
export const contracts = ['activated_at', 'activated_by', 'contract_number', 'contract_type', 'created_at', 'created_by', 'currency', 'deleted_at', 'description', 'end_date', 'exchange_rate', 'id', 'notes', 'organization_id', 'party_id', 'party_type', 'payment_terms', 'renewed_from_id', 'start_date', 'status', 'tax_rate', 'terminated_at', 'terminated_by', 'termination_reason', 'terms', 'total_amount', 'updated_at'] as const;
export const cost_centers = ['code', 'created_at', 'deleted_at', 'id', 'is_active', 'manager_id', 'name', 'organization_id', 'parent_id', 'updated_at'] as const;
export const currencies = ['currency_code', 'currency_name', 'decimal_places', 'is_active', 'symbol'] as const;
export const customer_addresses = ['address', 'address_type', 'city', 'contact_name', 'contact_phone', 'country', 'created_at', 'customer_id', 'id', 'is_default', 'postal_code', 'province'] as const;
export const customer_bank_accounts = ['account_name', 'account_number', 'bank_name', 'created_at', 'currency', 'customer_id', 'deleted_at', 'id', 'is_default', 'organization_id', 'swift_code', 'updated_at'] as const;
export const customer_receipts = ['amount', 'created_at', 'created_by', 'customer_id', 'deleted_at', 'id', 'notes', 'organization_id', 'payment_method', 'receipt_date', 'receipt_number', 'reference_id', 'reference_type', 'status', 'updated_at'] as const;
export const customers = ['classification', 'code', 'contact', 'created_at', 'created_by', 'credit_limit', 'default_address_id', 'deleted_at', 'email', 'id', 'name', 'organization_id', 'payment_terms', 'phone', 'short_name', 'status', 'tax_number', 'type', 'updated_at'] as const;
export const defect_codes = ['category', 'code', 'created_at', 'deleted_at', 'description', 'id', 'is_active', 'name', 'organization_id', 'severity'] as const;
export const departments = ['code', 'created_at', 'id', 'manager_id', 'name', 'organization_id', 'parent_id', 'status', 'updated_at'] as const;
export const document_attachments = ['created_at', 'entity_id', 'entity_type', 'file_name', 'file_path', 'file_size', 'id', 'mime_type', 'organization_id', 'uploaded_by'] as const;
export const document_relations = ['created_at', 'from_object_id', 'from_object_type', 'id', 'label', 'metadata', 'organization_id', 'relation_type', 'to_object_id', 'to_object_type', 'updated_at'] as const;
export const dynamic_form_data = ['created_at', 'created_by', 'data', 'deleted_at', 'id', 'is_sandbox', 'organization_id', 'schema_registry_id', 'updated_at'] as const;
export const employees = ['created_at', 'department_id', 'email', 'employee_number', 'hire_date', 'id', 'name', 'organization_id', 'phone', 'position', 'status', 'updated_at', 'user_id'] as const;
export const exchange_rates = ['created_at', 'effective_date', 'expiry_date', 'from_currency', 'id', 'organization_id', 'rate', 'rate_type', 'to_currency'] as const;
export const failed_login_attempts = ['created_at', 'id', 'ip_address', 'reason', 'username'] as const;
export const fixed_assets = ['acquisition_cost', 'acquisition_date', 'asset_name', 'asset_number', 'category', 'cost_center_id', 'created_at', 'created_by', 'current_book_value', 'custodian_id', 'deleted_at', 'department', 'depreciation_method', 'id', 'location', 'notes', 'organization_id', 'salvage_value', 'status', 'updated_at', 'useful_life_months'] as const;
export const import_logs = ['completed_at', 'error_count', 'errors', 'file_name', 'id', 'imported_by', 'organization_id', 'resource_type', 'started_at', 'status', 'success_count', 'total_rows'] as const;
export const inventory_count_lines = ['counted_quantity', 'id', 'inventory_count_id', 'notes', 'product_id', 'storage_location_id', 'system_quantity', 'variance_quantity'] as const;
export const inventory_counts = ['approved_by', 'count_date', 'count_number', 'created_at', 'created_by', 'deleted_at', 'id', 'notes', 'organization_id', 'status', 'updated_at', 'warehouse_id'] as const;
export const inventory_lots = ['created_at', 'deleted_at', 'expiry_date', 'id', 'lot_number', 'manufacture_date', 'organization_id', 'product_id', 'quantity', 'status', 'updated_at', 'warehouse_id'] as const;
export const inventory_reservations = ['created_at', 'expires_at', 'id', 'organization_id', 'product_id', 'reference_id', 'reference_type', 'reserved_by', 'reserved_quantity', 'status', 'updated_at', 'warehouse_id'] as const;
export const message_feedback = ['comment', 'created_at', 'feedback', 'id', 'message_id', 'organization_id', 'session_id', 'user_id'] as const;
export const notifications = ['body', 'created_at', 'entity_id', 'entity_type', 'id', 'is_read', 'notification_type', 'organization_id', 'read_at', 'recipient_id', 'title'] as const;
export const number_sequences = ['created_at', 'current_value', 'id', 'increment_by', 'organization_id', 'padding', 'prefix', 'sequence_name', 'updated_at'] as const;
export const organization_currencies = ['created_at', 'currency_code', 'id', 'is_default', 'organization_id'] as const;
export const organization_uoms = ['created_at', 'id', 'is_default', 'organization_id', 'uom_id'] as const;
export const organizations = ['address', 'code', 'created_at', 'email', 'id', 'name', 'phone', 'plan', 'settings', 'status', 'tax_number', 'updated_at'] as const;
export const payment_records = ['account_subject_id', 'amount', 'created_at', 'created_by', 'id', 'notes', 'organization_id', 'partner_id', 'partner_type', 'payment_date', 'payment_method', 'payment_number', 'payment_type', 'reference_id', 'reference_type', 'status', 'updated_at', 'voucher_id'] as const;
export const payment_requests = ['amount', 'approved_at', 'approved_by', 'bank_account_id', 'created_at', 'created_by', 'currency', 'deleted_at', 'due_date', 'id', 'notes', 'ok_to_pay', 'organization_id', 'payment_method', 'rejected_at', 'rejected_by', 'rejection_reason', 'request_number', 'statement_id', 'status', 'submitted_at', 'submitted_by', 'supplier_id', 'supplier_invoice_id', 'updated_at'] as const;
export const portal_users = ['created_at', 'deleted_at', 'id', 'last_login_at', 'password_changed_at', 'password_hash', 'role', 'status', 'supplier_id', 'updated_at', 'username'] as const;
export const price_list_lines = ['created_at', 'deleted_at', 'discount_rate', 'effective_from', 'effective_to', 'id', 'min_quantity', 'price_list_id', 'product_id', 'unit_price'] as const;
export const price_lists = ['code', 'created_at', 'currency', 'deleted_at', 'effective_from', 'effective_to', 'id', 'is_default', 'name', 'organization_id', 'status', 'updated_at'] as const;
export const product_categories = ['code', 'created_at', 'id', 'is_active', 'level', 'name', 'organization_id', 'parent_id', 'updated_at'] as const;
export const product_cost_history = ['cost_method', 'created_at', 'effective_date', 'id', 'organization_id', 'product_id', 'reference_id', 'reference_type', 'total_quantity', 'total_value', 'unit_cost'] as const;
export const products = ['average_daily_consumption', 'brand', 'category_id', 'code', 'cost_price', 'created_at', 'created_by', 'default_tax_code', 'deleted_at', 'description', 'id', 'is_active', 'is_lot_controlled', 'is_serial_controlled', 'item_type', 'list_price', 'max_stock', 'min_stock', 'name', 'organization_id', 'requires_inspection', 'safety_stock', 'safety_stock_days', 'sale_price', 'sku_code', 'specification', 'standard_cost', 'status', 'type', 'unit', 'uom', 'updated_at'] as const;
export const profile_change_requests = ['after_data', 'before_data', 'change_request_id', 'created_at', 'created_by', 'id', 'organization_id', 'request_type', 'status', 'supplier_id', 'updated_at'] as const;
export const purchase_order_items = ['amount', 'deleted_at', 'id', 'invoiced_quantity', 'line_number', 'notes', 'product_id', 'purchase_order_id', 'quantity', 'received_quantity', 'tax_rate', 'unit_price'] as const;
export const purchase_orders = ['approved_at', 'approved_by', 'created_at', 'created_by', 'currency', 'decision_id', 'deleted_at', 'expected_date', 'id', 'notes', 'order_date', 'order_number', 'organization_id', 'payment_terms', 'rejected_at', 'rejected_by', 'rejection_reason', 'status', 'submitted_at', 'submitted_by', 'supplier_id', 'tax_amount', 'total_amount', 'updated_at', 'warehouse_id'] as const;
export const purchase_receipt_items = ['amount', 'id', 'lot_number', 'notes', 'product_id', 'purchase_order_item_id', 'purchase_receipt_id', 'quantity', 'unit_price'] as const;
export const purchase_receipts = ['confirmed_at', 'confirmed_by', 'created_at', 'created_by', 'deleted_at', 'id', 'notes', 'organization_id', 'purchase_order_id', 'receipt_date', 'receipt_number', 'status', 'supplier_id', 'updated_at', 'warehouse_id'] as const;
export const purchase_requisition_lines = ['amount', 'deleted_at', 'id', 'line_number', 'notes', 'product_id', 'purchase_requisition_id', 'quantity', 'suggested_supplier_id', 'unit_price'] as const;
export const purchase_requisitions = ['approved_at', 'approved_by', 'created_at', 'created_by', 'deleted_at', 'department_id', 'id', 'notes', 'organization_id', 'rejected_at', 'rejected_by', 'rejection_reason', 'request_date', 'requester_id', 'required_date', 'requisition_number', 'status', 'submitted_at', 'submitted_by', 'total_amount', 'updated_at'] as const;
export const quality_inspection_items = ['check_item', 'check_result', 'check_standard', 'id', 'measured_value', 'notes', 'quality_inspection_id'] as const;
export const quality_inspections = ['completed_at', 'completed_by', 'created_at', 'created_by', 'defective_quantity', 'deleted_at', 'id', 'inspection_date', 'inspection_number', 'inspector_id', 'notes', 'organization_id', 'product_id', 'purchase_receipt_item_id', 'qualified_quantity', 'reference_id', 'reference_type', 'result', 'status', 'total_quantity', 'updated_at'] as const;
export const quality_standard_items = ['acceptance_criteria', 'check_method', 'created_at', 'deleted_at', 'id', 'is_mandatory', 'item_name', 'sequence_order', 'standard_id'] as const;
export const quality_standards = ['created_at', 'deleted_at', 'description', 'id', 'is_active', 'organization_id', 'standard_code', 'standard_name', 'updated_at'] as const;
export const reconciliation_lines = ['created_at', 'deleted_at', 'description', 'id', 'item_id', 'line_amount', 'notes', 'quantity', 'statement_id', 'unit_price'] as const;
export const reconciliation_statements = ['created_at', 'currency', 'deleted_at', 'id', 'notes', 'organization_id', 'paid_amount', 'period_end', 'period_start', 'statement_no', 'statement_period', 'status', 'supplier_id', 'total_amount', 'updated_at'] as const;
export const rfq_headers = ['created_at', 'created_by', 'deleted_at', 'due_date', 'id', 'issued_at', 'issued_by', 'notes', 'organization_id', 'purchase_request_id', 'rfq_number', 'status', 'updated_at'] as const;
export const rfq_lines = ['created_at', 'deleted_at', 'description', 'id', 'line_number', 'product_id', 'qty_requested', 'rfq_id', 'unit_of_measure', 'updated_at'] as const;
export const role_permissions = ['action', 'conditions', 'created_at', 'id', 'resource', 'role_id'] as const;
export const roles = ['created_at', 'description', 'id', 'is_system', 'name', 'organization_id', 'updated_at'] as const;
export const sales_invoice_items = ['amount', 'deleted_at', 'discount_rate', 'id', 'product_id', 'quantity', 'sales_invoice_id', 'sales_order_item_id', 'sales_shipment_item_id', 'tax_rate', 'unit_price'] as const;
export const sales_invoices = ['created_at', 'created_by', 'currency', 'customer_id', 'deleted_at', 'due_date', 'id', 'invoice_date', 'invoice_number', 'notes', 'organization_id', 'payment_terms', 'sales_order_id', 'status', 'tax_amount', 'total_amount', 'updated_at'] as const;
export const sales_order_items = ['amount', 'deleted_at', 'discount_rate', 'id', 'invoiced_quantity', 'line_number', 'notes', 'product_id', 'quantity', 'sales_order_id', 'shipped_quantity', 'tax_rate', 'unit_price'] as const;
export const sales_orders = ['approved_at', 'approved_by', 'cancellation_reason', 'cancelled_at', 'cancelled_by', 'created_at', 'created_by', 'currency', 'customer_id', 'deleted_at', 'delivery_date', 'id', 'notes', 'order_date', 'order_number', 'organization_id', 'payment_status', 'payment_terms', 'rejected_at', 'rejected_by', 'rejection_reason', 'status', 'submitted_at', 'submitted_by', 'tax_amount', 'total_amount', 'updated_at', 'warehouse_id'] as const;
export const sales_return_items = ['amount', 'deleted_at', 'id', 'product_id', 'quantity', 'reason', 'sales_return_id', 'unit_price'] as const;
export const sales_returns = ['created_at', 'created_by', 'customer_id', 'deleted_at', 'id', 'notes', 'organization_id', 'reason', 'received_at', 'return_date', 'return_number', 'sales_order_id', 'status', 'total_amount', 'updated_at', 'warehouse_id'] as const;
export const sales_shipment_items = ['amount', 'deleted_at', 'id', 'notes', 'product_id', 'quantity', 'sales_order_item_id', 'sales_shipment_id', 'unit_price'] as const;
export const sales_shipments = ['carrier', 'confirmed_at', 'confirmed_by', 'created_at', 'created_by', 'customer_id', 'deleted_at', 'id', 'notes', 'organization_id', 'sales_order_id', 'shipment_date', 'shipment_number', 'shipping_method', 'status', 'tracking_number', 'updated_at', 'warehouse_id'] as const;
export const schema_registry = ['activated_at', 'archived_at', 'created_at', 'created_by', 'deleted_at', 'description', 'expires_at', 'id', 'json_schema', 'name', 'organization_id', 'risk_level', 'risk_score', 'slug', 'status', 'trace_id', 'ui_schema', 'updated_at', 'version'] as const;
export const schema_versions = ['created_at', 'created_by', 'id', 'json_schema', 'schema_diff', 'schema_id', 'ui_schema', 'version'] as const;
export const semantic_metadata = ['ai_hints', 'business_rules', 'column_name', 'created_at', 'data_type', 'description', 'display_name', 'id', 'table_name', 'updated_at', 'version'] as const;
export const serial_numbers = ['created_at', 'deleted_at', 'id', 'organization_id', 'product_id', 'purchase_order_id', 'received_at', 'sales_order_id', 'serial_number', 'shipped_at', 'status', 'updated_at', 'warehouse_id'] as const;
export const shipment_tracking_events = ['created_at', 'event_type', 'id', 'location', 'notes', 'occurred_at', 'organization_id', 'shipment_id'] as const;
export const stock_records = ['available_quantity', 'id', 'organization_id', 'product_id', 'quantity', 'reserved_quantity', 'updated_at', 'warehouse_id'] as const;
export const stock_transactions = ['created_at', 'created_by', 'id', 'notes', 'organization_id', 'product_id', 'quantity', 'reference_id', 'reference_type', 'transaction_date', 'transaction_type', 'warehouse_id'] as const;
export const storage_locations = ['code', 'created_at', 'deleted_at', 'id', 'is_active', 'name', 'organization_id', 'updated_at', 'warehouse_id', 'zone'] as const;
export const supplier_bank_accounts = ['account_name', 'account_number', 'bank_code', 'bank_name', 'created_at', 'currency', 'deleted_at', 'id', 'is_active', 'is_default', 'organization_id', 'supplier_id', 'swift_code', 'updated_at'] as const;
export const supplier_certificates = ['attachment_url', 'certificate_number', 'certificate_type', 'created_at', 'deleted_at', 'expiry_date', 'id', 'issued_by', 'issued_date', 'organization_id', 'status', 'supplier_id', 'updated_at', 'uploaded_at', 'uploaded_by'] as const;
export const supplier_contacts = ['created_at', 'deleted_at', 'email', 'id', 'is_default', 'name', 'organization_id', 'phone', 'supplier_id', 'title', 'updated_at'] as const;
export const supplier_invoice_items = ['amount', 'id', 'product_id', 'purchase_order_item_id', 'purchase_receipt_item_id', 'quantity', 'supplier_invoice_id', 'tax_rate', 'unit_price'] as const;
export const supplier_invoices = ['created_at', 'created_by', 'currency', 'deleted_at', 'due_date', 'id', 'invoice_date', 'invoice_number', 'notes', 'organization_id', 'purchase_order_id', 'status', 'supplier_id', 'tax_amount', 'total_amount', 'updated_at', 'uploaded_by'] as const;
export const supplier_quotation_lines = ['created_at', 'deleted_at', 'description', 'id', 'lead_time_days', 'product_id', 'qty_offered', 'quotation_id', 'rfq_line_id', 'total_price', 'unit_price', 'updated_at'] as const;
export const supplier_quotations = ['created_at', 'currency', 'deleted_at', 'id', 'notes', 'organization_id', 'quotation_number', 'rfq_id', 'status', 'supplier_id', 'updated_at', 'validity_date'] as const;
export const supplier_sites = ['address', 'city', 'contact_name', 'contact_phone', 'country', 'created_at', 'deleted_at', 'id', 'is_active', 'organization_id', 'postal_code', 'province', 'site_code', 'site_name', 'supplier_id', 'updated_at'] as const;
export const suppliers = ['code', 'contact_email', 'contact_person', 'contact_phone', 'created_at', 'created_by', 'currency', 'default_site_id', 'deleted_at', 'id', 'lead_time_days', 'name', 'notes', 'organization_id', 'payment_terms', 'reliability_score', 'short_name', 'status', 'supplier_type', 'tax_number', 'updated_at', 'website'] as const;
export const three_way_match_results = ['amount_variance', 'created_at', 'id', 'match_status', 'matched_at', 'matched_by', 'notes', 'organization_id', 'price_variance', 'purchase_order_id', 'purchase_receipt_id', 'quantity_variance', 'supplier_invoice_id'] as const;
export const token_usage = ['cost_estimate', 'created_at', 'id', 'input_tokens', 'model', 'organization_id', 'output_tokens', 'session_id', 'total_tokens', 'variant'] as const;
export const tool_call_metrics = ['cache_hit', 'created_at', 'duration_ms', 'error_message', 'id', 'input_hash', 'organization_id', 'session_id', 'success', 'tool_name'] as const;
export const tool_registry = ['active', 'audit_required', 'created_at', 'description', 'domain', 'input_schema', 'organization_id', 'output_schema', 'requires_permission', 'risk_level', 'tool_name', 'updated_at', 'version'] as const;
export const uoms = ['base_uom_id', 'conversion_factor', 'id', 'uom_code', 'uom_name', 'uom_type'] as const;
export const user_roles = ['assigned_at', 'assigned_by', 'id', 'organization_id', 'role_id', 'user_id'] as const;
export const v_customer_summary = ['code', 'credit_limit', 'id', 'name', 'order_count', 'organization_id', 'status', 'total_order_amount', 'type', 'unpaid_orders'] as const;
export const v_low_stock_alerts = ['alert_level', 'available_quantity', 'average_daily_consumption', 'days_of_stock', 'min_stock', 'organization_id', 'product_code', 'product_id', 'product_name', 'safety_stock_days', 'warehouse_id', 'warehouse_name'] as const;
export const v_pending_approvals = ['agent_id', 'confidence', 'created_at', 'decision', 'decision_id', 'organization_id', 'reasoning_summary', 'requested_by_name', 'risk_level', 'tools_called'] as const;
export const v_purchase_order_summary = ['created_at', 'currency', 'expected_date', 'id', 'line_count', 'order_date', 'order_number', 'organization_id', 'status', 'supplier_id', 'supplier_name', 'total_amount', 'total_quantity', 'total_received'] as const;
export const v_sales_order_summary = ['created_at', 'currency', 'customer_id', 'customer_name', 'delivery_date', 'id', 'line_count', 'order_date', 'order_number', 'organization_id', 'payment_status', 'status', 'total_amount', 'total_quantity', 'total_shipped'] as const;
export const v_stock_summary = ['id', 'max_stock', 'min_stock', 'organization_id', 'product_code', 'product_id', 'product_name', 'quantity_available', 'quantity_on_hand', 'quantity_reserved', 'stock_status', 'unit', 'updated_at', 'warehouse_id', 'warehouse_name'] as const;
export const v_supplier_summary = ['code', 'id', 'name', 'open_orders', 'order_count', 'organization_id', 'reliability_score', 'status', 'supplier_type', 'total_order_amount'] as const;
export const voucher_entries = ['account_subject_id', 'amount', 'entry_type', 'id', 'sequence', 'summary', 'voucher_id'] as const;
export const vouchers = ['approved_at', 'approved_by', 'created_at', 'created_by', 'id', 'notes', 'organization_id', 'posted_at', 'posted_by', 'status', 'total_credit', 'total_debit', 'updated_at', 'void_reason', 'voided_at', 'voided_by', 'voucher_date', 'voucher_number', 'voucher_type'] as const;
export const warehouses = ['code', 'created_at', 'deleted_at', 'id', 'location', 'manager_id', 'name', 'organization_id', 'status', 'type', 'updated_at'] as const;
export const work_order_materials = ['id', 'issued_quantity', 'notes', 'product_id', 'required_quantity', 'status', 'warehouse_id', 'work_order_id'] as const;
export const work_order_productions = ['created_at', 'created_by', 'defective_quantity', 'id', 'notes', 'production_date', 'qualified_quantity', 'quantity', 'work_order_id'] as const;
export const work_orders = ['actual_completion_date', 'approved_by', 'bom_header_id', 'completed_quantity', 'created_at', 'created_by', 'id', 'notes', 'organization_id', 'planned_completion_date', 'planned_quantity', 'product_id', 'start_date', 'status', 'updated_at', 'warehouse_id', 'work_order_number'] as const;
export const workflow_steps = ['action', 'assignee_role', 'completed_at', 'completed_by', 'condition', 'created_at', 'id', 'status', 'step_name', 'step_order', 'step_type', 'workflow_id'] as const;
export const workflows = ['completed_at', 'created_at', 'current_step', 'entity_id', 'entity_type', 'id', 'metadata', 'organization_id', 'started_at', 'started_by', 'status', 'workflow_type'] as const;

export const TABLE_COLUMNS: Record<string, readonly string[]> = {
  account_subjects,
  advance_shipment_notices,
  agent_decisions,
  agent_sessions,
  approval_records,
  approval_rule_steps,
  approval_rules,
  asn_lines,
  asset_depreciations,
  asset_maintenance_records,
  auth_events,
  bom_headers,
  bom_items,
  budget_lines,
  budgets,
  business_events,
  carriers,
  component_whitelist,
  contract_items,
  contracts,
  cost_centers,
  currencies,
  customer_addresses,
  customer_bank_accounts,
  customer_receipts,
  customers,
  defect_codes,
  departments,
  document_attachments,
  document_relations,
  dynamic_form_data,
  employees,
  exchange_rates,
  failed_login_attempts,
  fixed_assets,
  import_logs,
  inventory_count_lines,
  inventory_counts,
  inventory_lots,
  inventory_reservations,
  message_feedback,
  notifications,
  number_sequences,
  organization_currencies,
  organization_uoms,
  organizations,
  payment_records,
  payment_requests,
  portal_users,
  price_list_lines,
  price_lists,
  product_categories,
  product_cost_history,
  products,
  profile_change_requests,
  purchase_order_items,
  purchase_orders,
  purchase_receipt_items,
  purchase_receipts,
  purchase_requisition_lines,
  purchase_requisitions,
  quality_inspection_items,
  quality_inspections,
  quality_standard_items,
  quality_standards,
  reconciliation_lines,
  reconciliation_statements,
  rfq_headers,
  rfq_lines,
  role_permissions,
  roles,
  sales_invoice_items,
  sales_invoices,
  sales_order_items,
  sales_orders,
  sales_return_items,
  sales_returns,
  sales_shipment_items,
  sales_shipments,
  schema_registry,
  schema_versions,
  semantic_metadata,
  serial_numbers,
  shipment_tracking_events,
  stock_records,
  stock_transactions,
  storage_locations,
  supplier_bank_accounts,
  supplier_certificates,
  supplier_contacts,
  supplier_invoice_items,
  supplier_invoices,
  supplier_quotation_lines,
  supplier_quotations,
  supplier_sites,
  suppliers,
  three_way_match_results,
  token_usage,
  tool_call_metrics,
  tool_registry,
  uoms,
  user_roles,
  v_customer_summary,
  v_low_stock_alerts,
  v_pending_approvals,
  v_purchase_order_summary,
  v_sales_order_summary,
  v_stock_summary,
  v_supplier_summary,
  voucher_entries,
  vouchers,
  warehouses,
  work_order_materials,
  work_order_productions,
  work_orders,
  workflow_steps,
  workflows,
};
